import { describe, expect, it } from "vitest";

import * as root from "../index";
import * as core from "../core";
import * as engine from "../core/runtime/engine";
import * as http from "../http";
import * as httpTesting from "../http/testing";
import * as schema from "../schema";
import * as observability from "../observability";
import * as compression from "../http/compression";
import * as lifecycle from "../http/lifecycle";

describe("public barrel modules", () => {
  it("load the runtime, core, engine, HTTP, compression, and lifecycle barrels", async () => {
    await import("../core/runtime/events");
    await import("../core/runtime/engine/types");
    await import("../http/lifecycle/types");

    expect(root.Runtime).toBe(core.Runtime);
    expect(root.asyncSucceed).toBe(core.asyncSucceed);
    expect(root.Resource).toBe(core.Resource);
    expect(root.makeResource).toBe(core.makeResource);
    expect(root.fibonacci).toBe(core.fibonacci);
    expect(root.windowed).toBe(core.windowed);
    expect(root.jitter).toBe(core.jitter);
    expect(root.Supervisor).toBe(core.Supervisor);
    expect(root.makeSupervisor).toBe(core.makeSupervisor);
    expect(root.EventBus).toBe(core.EventBus);
    expect(root.consoleJsonLogger).toBe(core.consoleJsonLogger);
    expect(root.RuntimeRegistry).toBe(core.RuntimeRegistry);
    expect(root.InMemoryTracer).toBe(core.InMemoryTracer);
    expect(root.defaultTracer).toBe(core.defaultTracer);
    expect(engine.JsFiberEngine).toBeTypeOf("function");
    expect(http.makeHttpClient).toBeTypeOf("function");
    expect(http.makeDefaultHttpClient).toBeTypeOf("function");
    expect(http.httpClientBuilder).toBeTypeOf("function");
    expect(http.makeHttpRouter).toBeTypeOf("function");
    expect(http.route).toBeTypeOf("function");
    expect(http.makeNodeHttpServer).toBeTypeOf("function");
    expect(http.makeHttpServerResource).toBeTypeOf("function");
    expect(http.makeRuntimeHealthRoute).toBeTypeOf("function");
    expect(http.makeRuntimeReadinessRoute).toBeTypeOf("function");
    expect(http.adaptiveLimiterPresets).toBeTypeOf("object");
    expect(http.makeAdaptiveLimiterConfig).toBeTypeOf("function");
    expect(http.s.object).toBeTypeOf("function");
    expect(http.isHttpError).toBeTypeOf("function");
    expect(http.formatHttpError).toBeTypeOf("function");
    expect(httpTesting.makeMockHttpClient).toBeTypeOf("function");
    expect(httpTesting.withMockFetch).toBeTypeOf("function");
    expect(schema.s.object).toBeTypeOf("function");
    expect(schema.s.email).toBeTypeOf("function");
    expect(schema.s.nonEmptyString).toBeTypeOf("function");
    expect(schema.Schema.object).toBeTypeOf("function");
    expect(http.s).toBe(schema.s);
    expect(observability.formatPrometheusMetrics).toBeTypeOf("function");
    expect(observability.makeObservability).toBeTypeOf("function");
    expect(observability.withHttpObservability).toBeTypeOf("function");
    expect(observability.makeStructuredLogSink).toBeTypeOf("function");
    expect(observability.withSpan).toBeTypeOf("function");
    expect(observability.parseTraceparent).toBeTypeOf("function");
    expect(observability.makeRequestObservabilityContext).toBeTypeOf("function");
    expect(observability.makeExportPipeline).toBeTypeOf("function");
    expect(observability.ratioSampler).toBeTypeOf("function");
    expect(observability.makeObservabilityFromEnv).toBeTypeOf("function");
    expect(observability.makeExpressRequestObservabilityContext).toBeTypeOf("function");
    expect(observability.runObservedHttpServerEffect).toBeTypeOf("function");
    expect(observability.makeRuntimeHealth).toBeTypeOf("function");
    expect(observability.readiness).toBeTypeOf("function");
    expect(observability.structuredLogsToOtlp).toBeTypeOf("function");
    expect(http.makeCompressionMiddleware).toBe(compression.makeCompressionMiddleware);
    expect(http.makeLifecycleClient).toBe(lifecycle.makeLifecycleClient);
  });
});
